[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AcademicPaperGatherer"
version = "1.1.0"
description = "A modular data gathering and processing pipeline with Google Scholar and ArXiv support."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Autumn Clark" }
]

dependencies = [
    "beautifulsoup4==4.13.4",
    "certifi==2025.7.9",
    "charset-normalizer==3.4.2",
    "free-proxy==1.1.3",
    "fuzzywuzzy==0.18.0",
    "idna==3.10",
    "Levenshtein==0.27.1",
    "lxml==6.0.0",
    "PyMuPDF==1.26.3",
    "PyPDF2==3.0.1",
    "python-Levenshtein==0.27.1",
    "RapidFuzz==3.13.0",
    "requests==2.32.4",
    "soupsieve==2.7",
    "typing_extensions==4.14.1",
    "urllib3==2.5.0"
]

[project.scripts]
APG = "AcademicPaperGatherer.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["AcademicPaperGatherer*"]